# Generated by Django 2.2.3 on 2019-07-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0001_initial")]

    operations = [
        migrations.AlterUniqueTogether(
            name="dependency", unique_together={("name", "version")}
        )
    ]
