# Generated by Django 2.2.3 on 2019-07-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190722_1739'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('name', 'dependency')},
        ),
    ]
