# Generated by Django 2.2.3 on 2019-07-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190731_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='requires_python',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
