# Generated by Django 2.2.3 on 2019-07-31 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0008_auto_20190731_0406")]

    operations = [migrations.RemoveField(model_name="dependency", name="requires_dist")]
